language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - nightly
  - pypy

script:
  - python setup.py test
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pylint minfraud; fi

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
